language: php

php:
  - 5.4
  - 5.5
  - 7.0

before_script:
  - composer install --prefer-source
  - ln -s ./bin/wp-enforcer ./vendor/bin/wp-enforcer

script:
  - ./vendor/bin/wp-enforcer

cache:
  directories:
    - vendor/

notifications:
  email: false